---
# tasks file for 
- name: setup sampleuser
  user: name=sampleuser

- name: install git
  apt: name=git

- name: create dir for app
  file: path=/var/www/html/sample_app state=directory owner=sampleuser

- name: checkout the app code
  git: repo=https://github.com/chaochaoliu/2015-dev-ops-sample-application.git dest=/var/www/html/sample_app 

- name: install app dependencies
  command: php composer.phar install chdir=/var/www/html/sample_app
  become_user: sampleuser

- name: db migration
  command: php vendor/bin/phinx migrate -e production chdir=/var/www/html/sample_app 
  become_user: sampleuser
